version: "3"

services:
  mysql-dev:
    image: mysql:8.0.2
    container_name: mysql.ios_app.docker
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ESTIMOTE
    ports:
      - "3308:3306"

  postgres:
    image: postgres:latest
    container_name: postgres.ios_app.docker
    environment:
      POSTGRES_PASSWORD: password

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher.ios_app.docker
    restart: unless-stopped
    ports:
      - 127.0.0.1:1026:1026
      - 127.0.0.1:1081:1081
    networks:
      - global

networks:
  global:
    external: true
